ratings:
  paths:
  - "**.js"
  - "**.css"
  - "**.php"
exclude_paths:
  - "Gruntfile.js"
  - "bin/"
  - "lib/admin/CMB2/"
  - "lib/icons/"
  - "tests/"
  - "templates/"
  - "node_modules/"
  - "build/"
  - "lib/admin/js/bootstrap-select.js"
