engines:
  rubocop:
    enabled: false
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.ruleset.xml"
ratings:
  paths:
  - "**.js"
  - "**.css"
  - "**.php"
exclude_paths:
- bin/
- lib/admin/CMB2/
- lib/icons/
- tests/
- templates/
